image: node:14.18

cache:
  untracked: true
  paths:
    - .env
    - node_modules/

stages:
  - build
  - deploy

build:
  image: node:14.18
  stage: build
  variables:
    ENV_FILE: ENV_PROD
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /prod-.+/
      variables:
        ENV: production
        ENV_FILE: $ENV_PROD
    - if: $CI_COMMIT_REF_NAME =~ /dev-.+/
      variables:
        ENV: development
        ENV_FILE: $ENV_DEV
  artifacts:
    paths:
      - .nuxt
  script:
    - printf "%s\n" $ENV_FILE > .env
    - npm install --only=prod
    - npm run build
  environment: $ENV

deploy:
  image: python:latest
  stage: deploy
  variables:
    ENV: development
    EB_APP_NAME: rea-ssr
    EB_S3_BUCKET: 8prop-app
    VPC_ID: $VPC_ID_DEV
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /prod-.+/
      variables:
        ENV: production
        VPC_ID: $VPC_ID_PROD
        SHORT_ENV: prod
    - if: $CI_COMMIT_REF_NAME =~ /dev-.+/
      variables:
        VPC_ID: $VPC_ID_DEV
        ENV: development
        SHORT_ENV: dev
  before_script:
    - pip install --upgrade awscli zip-files
  script:
    - chmod a+x bin-deploy/deploy.sh
    - ./bin-deploy/deploy.sh
  environment: $ENV
  dependencies:
    - build
