org: amandine
app: rea
service: rea

plugins:
  - serverless-offline
  # - serverless-nuxt-plugin
  - serverless-apigw-binary
  # - serverless-domain-manager

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    SLS_DEBUG: '*'

custom:
  customDomain:
    domainName: 'rea-id.com'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: '*.rea-id.com.'
  apigwBinary:
    types:
      - 'image/*'

functions:
  nuxt:
    timeout: 30
    # handler: handler.render
    # handler: app.handler
    handler: app.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}