service: serverless-side-rendering-vue-nuxt

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:provider.stage}
  region: us-west-1
  environment: 
    NODE_ENV: ${self:provider.stage}

functions:
  nuxt:
    handler: index.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary
  - serverless-domain-manager

custom:
  secrets: ${file(secrets.json)}
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: 'serverless.rea-id.com'
    certificateName: '*.rea-id.com'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateArn: 'arn:aws:acm:ap-southeast-1:051694948699:certificate/6575dffb-289b-4a0a-a22b-8fc5929ecf65'